name: 'Download a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
  artifact-folder:
    description: 'Denotes if an extra directory is created for any artifacts that are downloaded'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'